database:
  provider: "postgresql"
  connection: "${DATABASE_URL}"
  pool_size: 10
  timeout: 30
  
  migrations:
    enabled: true
    directory: "./migrations"
  
  tables:
    users:
      id: "serial primary key"
      email: "varchar(255) unique not null"
      password_hash: "varchar(255) not null"
      name: "varchar(255) not null"
      created_at: "timestamp default now()"
      updated_at: "timestamp default now()"
      
      indexes:
        - name: "idx_users_email"
          columns: ["email"]
          unique: true
    
    tasks:
      id: "serial primary key"
      user_id: "integer not null references users(id) on delete cascade"
      title: "varchar(255) not null"
      description: "text"
      status: "varchar(50) default 'pending' check (status in ('pending', 'active', 'completed', 'cancelled'))"
      priority: "varchar(20) default 'medium' check (priority in ('low', 'medium', 'high', 'urgent'))"
      due_date: "timestamp"
      created_at: "timestamp default now()"
      updated_at: "timestamp default now()"
      
      indexes:
        - name: "idx_tasks_user_id"
          columns: ["user_id"]
        - name: "idx_tasks_status"
          columns: ["status"]
        - name: "idx_tasks_priority"
          columns: ["priority"]
        - name: "idx_tasks_due_date"
          columns: ["due_date"]
          
    task_categories:
      id: "serial primary key"
      user_id: "integer not null references users(id) on delete cascade"
      name: "varchar(100) not null"
      color: "varchar(7) default '#3b82f6'"
      created_at: "timestamp default now()"
      
      indexes:
        - name: "idx_task_categories_user_id"
          columns: ["user_id"]
    
    task_attachments:
      id: "serial primary key"
      task_id: "integer not null references tasks(id) on delete cascade"
      filename: "varchar(255) not null"
      file_path: "varchar(500) not null"
      file_size: "integer not null"
      mime_type: "varchar(100)"
      uploaded_at: "timestamp default now()"
      
      indexes:
        - name: "idx_task_attachments_task_id"
          columns: ["task_id"]

# Database functions and triggers
functions:
  update_updated_at:
    language: "plpgsql"
    body: |
      BEGIN
        NEW.updated_at = NOW();
        RETURN NEW;
      END;

triggers:
  users_updated_at:
    table: "users"
    event: "before update"
    function: "update_updated_at"
    
  tasks_updated_at:
    table: "tasks"
    event: "before update"
    function: "update_updated_at"

# Initial data seeding
seeds:
  - table: "users"
    data:
      - email: "demo@example.com"
        password_hash: "$2b$10$hash_here" # bcrypt hash of "password123"
        name: "Demo User"
        
  - table: "task_categories"
    data:
      - user_id: 1
        name: "Work"
        color: "#3b82f6"
      - user_id: 1
        name: "Personal"
        color: "#10b981"
      - user_id: 1
        name: "Urgent"
        color: "#ef4444"
